name: Build and upload to PyPI

on:
  schedule:
    # trigger build every day at 4:30 UTC
    - cron: '30 4 * * *'
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build web
        run: |
          pip install -r CI/requirements-wheel.txt
          cd python && python setup.py build_web && git reset --hard HEAD

      - name: Build sdist
        run: cd python && pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: ./python/dist/*.tar.gz

  upload_pypi:
    needs: [build_sdist]
    runs-on: ubuntu-latest
    # upload to PyPI on every tag starting with 'v'
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist

      # if is xprobe repo, upload to pypi
      - uses: pypa/gh-action-pypi-publish@v1.5.0
        if: github.repository == 'xorbitsai/xorbits'
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          skip-existing: true

      # if is not xprobe repo, upload to test
      - uses: pypa/gh-action-pypi-publish@v1.5.0
        if: github.repository != 'xorbitsai/xorbits'
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          verbose: true
          repository_url: https://test.pypi.org/legacy/
